### PR TITLE
Php 7 Tags

### LINKED ISSUE #19: Pets\Compound not found
Pets cannot find CompoundTag

### PR DESCRIPTION
**Pull request by ClockProgramming**
I fixes some php7 tags

### CODE REVIEW

**Comment by thelucyclub** [comment]
This plugin is for php5

**Comment by thelucyclub** [comment]
Works for me!

**Comment by thelucyclub** [comment]
Plugin now on IM! (Pending approval)

**Comment by jasonwynn10** [comment]
works on IM?

**Pull request merged**
