### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by thelucyclub**

### CODE REVIEW

**Comment by EpicSteve33** [comment]
you should merge this

**Comment by thelucyclub** [comment]
@EpicSteve33 Dude, i'm trying. I've been sitting at my PC for like an hour, the most recent thought of: "Where is the nearest cliff to throw this piece of :poop: off of?"

**Comment by thelucyclub** [comment]
Ok, I give up.

**Comment by EpicSteve33** [comment]
?

**Comment by thelucyclub** [comment]
@jasonwynn10 Heeelp.

**Comment by EpicSteve33** [comment]
maybe you could open a new branch and delete the master

**Comment by thelucyclub** [comment]
hmmm.. ok i'll try that.

**Comment by jasonwynn10** [comment]
I see you're having a time trying to fork over my code...

**Comment by thelucyclub** [comment]
Yes, but it is difficult.

**Comment by jasonwynn10** [comment]
Would you like me to fix this for you?

**Comment by jasonwynn10** [comment]
This can be closed

**Pull request closed without merging**
